// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package me.mervap.market;

public interface GCompanyDescOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.mervap.GCompanyDesc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string country = 3;</code>
   * @return The country.
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 3;</code>
   * @return The bytes for country.
   */
  com.google.protobuf.ByteString
      getCountryBytes();
}
