// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package me.mervap.market;

public interface GCompanyDescListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.mervap.GCompanyDescList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .me.mervap.GCompanyDesc companies = 1;</code>
   */
  java.util.List<me.mervap.market.GCompanyDesc> 
      getCompaniesList();
  /**
   * <code>repeated .me.mervap.GCompanyDesc companies = 1;</code>
   */
  me.mervap.market.GCompanyDesc getCompanies(int index);
  /**
   * <code>repeated .me.mervap.GCompanyDesc companies = 1;</code>
   */
  int getCompaniesCount();
  /**
   * <code>repeated .me.mervap.GCompanyDesc companies = 1;</code>
   */
  java.util.List<? extends me.mervap.market.GCompanyDescOrBuilder> 
      getCompaniesOrBuilderList();
  /**
   * <code>repeated .me.mervap.GCompanyDesc companies = 1;</code>
   */
  me.mervap.market.GCompanyDescOrBuilder getCompaniesOrBuilder(
      int index);
}
