// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package me.mervap.market;

public interface GOpStokDescOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.mervap.GOpStokDesc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 count = 2;</code>
   * @return The count.
   */
  int getCount();

  /**
   * <code>double budget = 3;</code>
   * @return The budget.
   */
  double getBudget();
}
