// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package me.mervap.market;

public interface GStockDescOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.mervap.GStockDesc)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 companyId = 2;</code>
   * @return The companyId.
   */
  int getCompanyId();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>double price = 4;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>int32 totalCount = 5;</code>
   * @return The totalCount.
   */
  int getTotalCount();
}
