// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package me.mervap.market;

public interface GStockDescListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.mervap.GStockDescList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .me.mervap.GStockDesc stocks = 1;</code>
   */
  java.util.List<me.mervap.market.GStockDesc> 
      getStocksList();
  /**
   * <code>repeated .me.mervap.GStockDesc stocks = 1;</code>
   */
  me.mervap.market.GStockDesc getStocks(int index);
  /**
   * <code>repeated .me.mervap.GStockDesc stocks = 1;</code>
   */
  int getStocksCount();
  /**
   * <code>repeated .me.mervap.GStockDesc stocks = 1;</code>
   */
  java.util.List<? extends me.mervap.market.GStockDescOrBuilder> 
      getStocksOrBuilderList();
  /**
   * <code>repeated .me.mervap.GStockDesc stocks = 1;</code>
   */
  me.mervap.market.GStockDescOrBuilder getStocksOrBuilder(
      int index);
}
