// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package me.mervap.market;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_mervap_GCompanyDesc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_mervap_GCompanyDesc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_mervap_GCompanyDescList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_mervap_GCompanyDescList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_mervap_GStockDesc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_mervap_GStockDesc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_mervap_GStockDescList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_mervap_GStockDescList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_mervap_GOpStokDesc_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_mervap_GOpStokDesc_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_me_mervap_GCommandResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_me_mervap_GCommandResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\022\tme.mervap\032\033google/proto" +
      "buf/empty.proto\032\036google/protobuf/wrapper" +
      "s.proto\"9\n\014GCompanyDesc\022\n\n\002id\030\001 \001(\005\022\014\n\004n" +
      "ame\030\002 \001(\t\022\017\n\007country\030\003 \001(\t\">\n\020GCompanyDe" +
      "scList\022*\n\tcompanies\030\001 \003(\0132\027.me.mervap.GC" +
      "ompanyDesc\"\\\n\nGStockDesc\022\n\n\002id\030\001 \001(\005\022\021\n\t" +
      "companyId\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\r\n\005price\030\004" +
      " \001(\001\022\022\n\ntotalCount\030\005 \001(\005\"7\n\016GStockDescLi" +
      "st\022%\n\006stocks\030\001 \003(\0132\025.me.mervap.GStockDes" +
      "c\"8\n\013GOpStokDesc\022\n\n\002id\030\001 \001(\005\022\r\n\005count\030\002 " +
      "\001(\005\022\016\n\006budget\030\003 \001(\001\"/\n\020GCommandResponse\022" +
      "\n\n\002ok\030\001 \001(\010\022\017\n\007message\030\002 \001(\t2\247\003\n\rMarketS" +
      "ervice\022D\n\nnewCompany\022\027.me.mervap.GCompan" +
      "yDesc\032\033.me.mervap.GCommandResponse\"\000\022@\n\010" +
      "newStock\022\025.me.mervap.GStockDesc\032\033.me.mer" +
      "vap.GCommandResponse\"\000\022A\n\010buyStock\022\026.me." +
      "mervap.GOpStokDesc\032\033.me.mervap.GCommandR" +
      "esponse\"\000\022B\n\tsellStock\022\026.me.mervap.GOpSt" +
      "okDesc\032\033.me.mervap.GCommandResponse\"\000\022D\n" +
      "\013companyList\022\026.google.protobuf.Empty\032\033.m" +
      "e.mervap.GCompanyDescList\"\000\022A\n\nstocksLis" +
      "t\022\026.google.protobuf.Empty\032\031.me.mervap.GS" +
      "tockDescList\"\000B\024\n\020me.mervap.marketP\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_me_mervap_GCompanyDesc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_me_mervap_GCompanyDesc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_mervap_GCompanyDesc_descriptor,
        new java.lang.String[] { "Id", "Name", "Country", });
    internal_static_me_mervap_GCompanyDescList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_me_mervap_GCompanyDescList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_mervap_GCompanyDescList_descriptor,
        new java.lang.String[] { "Companies", });
    internal_static_me_mervap_GStockDesc_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_me_mervap_GStockDesc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_mervap_GStockDesc_descriptor,
        new java.lang.String[] { "Id", "CompanyId", "Name", "Price", "TotalCount", });
    internal_static_me_mervap_GStockDescList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_me_mervap_GStockDescList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_mervap_GStockDescList_descriptor,
        new java.lang.String[] { "Stocks", });
    internal_static_me_mervap_GOpStokDesc_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_me_mervap_GOpStokDesc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_mervap_GOpStokDesc_descriptor,
        new java.lang.String[] { "Id", "Count", "Budget", });
    internal_static_me_mervap_GCommandResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_me_mervap_GCommandResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_me_mervap_GCommandResponse_descriptor,
        new java.lang.String[] { "Ok", "Message", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
