// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package me.mervap.message;

public interface GStatListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.mervap.GStatList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .me.mervap.GStat stats = 1;</code>
   */
  java.util.List<me.mervap.message.GStat> 
      getStatsList();
  /**
   * <code>repeated .me.mervap.GStat stats = 1;</code>
   */
  me.mervap.message.GStat getStats(int index);
  /**
   * <code>repeated .me.mervap.GStat stats = 1;</code>
   */
  int getStatsCount();
  /**
   * <code>repeated .me.mervap.GStat stats = 1;</code>
   */
  java.util.List<? extends me.mervap.message.GStatOrBuilder> 
      getStatsOrBuilderList();
  /**
   * <code>repeated .me.mervap.GStat stats = 1;</code>
   */
  me.mervap.message.GStatOrBuilder getStatsOrBuilder(
      int index);
}
