// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package me.mervap.message;

public interface GStatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.mervap.GStat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.me.mervap.GUserName userName = 2;</code>
   * @return Whether the userName field is set.
   */
  boolean hasUserName();
  /**
   * <code>.me.mervap.GUserName userName = 2;</code>
   * @return The userName.
   */
  me.mervap.message.GUserName getUserName();
  /**
   * <code>.me.mervap.GUserName userName = 2;</code>
   */
  me.mervap.message.GUserNameOrBuilder getUserNameOrBuilder();

  /**
   * <code>map&lt;int32, int32&gt; weekStat = 3;</code>
   */
  int getWeekStatCount();
  /**
   * <code>map&lt;int32, int32&gt; weekStat = 3;</code>
   */
  boolean containsWeekStat(
      int key);
  /**
   * Use {@link #getWeekStatMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getWeekStat();
  /**
   * <code>map&lt;int32, int32&gt; weekStat = 3;</code>
   */
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getWeekStatMap();
  /**
   * <code>map&lt;int32, int32&gt; weekStat = 3;</code>
   */

  int getWeekStatOrDefault(
      int key,
      int defaultValue);
  /**
   * <code>map&lt;int32, int32&gt; weekStat = 3;</code>
   */

  int getWeekStatOrThrow(
      int key);

  /**
   * <code>repeated int32 visitsAtWeek = 4;</code>
   * @return A list containing the visitsAtWeek.
   */
  java.util.List<java.lang.Integer> getVisitsAtWeekList();
  /**
   * <code>repeated int32 visitsAtWeek = 4;</code>
   * @return The count of visitsAtWeek.
   */
  int getVisitsAtWeekCount();
  /**
   * <code>repeated int32 visitsAtWeek = 4;</code>
   * @param index The index of the element to return.
   * @return The visitsAtWeek at the given index.
   */
  int getVisitsAtWeek(int index);

  /**
   * <code>repeated int64 visitsDuration = 5;</code>
   * @return A list containing the visitsDuration.
   */
  java.util.List<java.lang.Long> getVisitsDurationList();
  /**
   * <code>repeated int64 visitsDuration = 5;</code>
   * @return The count of visitsDuration.
   */
  int getVisitsDurationCount();
  /**
   * <code>repeated int64 visitsDuration = 5;</code>
   * @param index The index of the element to return.
   * @return The visitsDuration at the given index.
   */
  long getVisitsDuration(int index);

  /**
   * <code>.google.protobuf.Timestamp purchaseDate = 6;</code>
   * @return Whether the purchaseDate field is set.
   */
  boolean hasPurchaseDate();
  /**
   * <code>.google.protobuf.Timestamp purchaseDate = 6;</code>
   * @return The purchaseDate.
   */
  com.google.protobuf.Timestamp getPurchaseDate();
  /**
   * <code>.google.protobuf.Timestamp purchaseDate = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getPurchaseDateOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp lastEnter = 7;</code>
   * @return Whether the lastEnter field is set.
   */
  boolean hasLastEnter();
  /**
   * <code>.google.protobuf.Timestamp lastEnter = 7;</code>
   * @return The lastEnter.
   */
  com.google.protobuf.Timestamp getLastEnter();
  /**
   * <code>.google.protobuf.Timestamp lastEnter = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastEnterOrBuilder();
}
