// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package me.mervap.message;

/**
 * Protobuf type {@code me.mervap.GStat}
 */
public final class GStat extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:me.mervap.GStat)
    GStatOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GStat.newBuilder() to construct.
  private GStat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GStat() {
    id_ = "";
    visitsAtWeek_ = emptyIntList();
    visitsDuration_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GStat();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GStat(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            me.mervap.message.GUserName.Builder subBuilder = null;
            if (userName_ != null) {
              subBuilder = userName_.toBuilder();
            }
            userName_ = input.readMessage(me.mervap.message.GUserName.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(userName_);
              userName_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              weekStat_ = com.google.protobuf.MapField.newMapField(
                  WeekStatDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
            weekStat__ = input.readMessage(
                WeekStatDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            weekStat_.getMutableMap().put(
                weekStat__.getKey(), weekStat__.getValue());
            break;
          }
          case 32: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              visitsAtWeek_ = newIntList();
              mutable_bitField0_ |= 0x00000002;
            }
            visitsAtWeek_.addInt(input.readInt32());
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
              visitsAtWeek_ = newIntList();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              visitsAtWeek_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 40: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              visitsDuration_ = newLongList();
              mutable_bitField0_ |= 0x00000004;
            }
            visitsDuration_.addLong(input.readInt64());
            break;
          }
          case 42: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) != 0) && input.getBytesUntilLimit() > 0) {
              visitsDuration_ = newLongList();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              visitsDuration_.addLong(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
          case 50: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (purchaseDate_ != null) {
              subBuilder = purchaseDate_.toBuilder();
            }
            purchaseDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(purchaseDate_);
              purchaseDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (lastEnter_ != null) {
              subBuilder = lastEnter_.toBuilder();
            }
            lastEnter_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lastEnter_);
              lastEnter_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        visitsAtWeek_.makeImmutable(); // C
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        visitsDuration_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return me.mervap.message.Service.internal_static_me_mervap_GStat_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 3:
        return internalGetWeekStat();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return me.mervap.message.Service.internal_static_me_mervap_GStat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            me.mervap.message.GStat.class, me.mervap.message.GStat.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  private me.mervap.message.GUserName userName_;
  /**
   * <code>.me.mervap.GUserName userName = 2;</code>
   * @return Whether the userName field is set.
   */
  @java.lang.Override
  public boolean hasUserName() {
    return userName_ != null;
  }
  /**
   * <code>.me.mervap.GUserName userName = 2;</code>
   * @return The userName.
   */
  @java.lang.Override
  public me.mervap.message.GUserName getUserName() {
    return userName_ == null ? me.mervap.message.GUserName.getDefaultInstance() : userName_;
  }
  /**
   * <code>.me.mervap.GUserName userName = 2;</code>
   */
  @java.lang.Override
  public me.mervap.message.GUserNameOrBuilder getUserNameOrBuilder() {
    return getUserName();
  }

  public static final int WEEKSTAT_FIELD_NUMBER = 3;
  private static final class WeekStatDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.Integer, java.lang.Integer> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.Integer, java.lang.Integer>newDefaultInstance(
                me.mervap.message.Service.internal_static_me_mervap_GStat_WeekStatEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.INT32,
                0);
  }
  private com.google.protobuf.MapField<
      java.lang.Integer, java.lang.Integer> weekStat_;
  private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
  internalGetWeekStat() {
    if (weekStat_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          WeekStatDefaultEntryHolder.defaultEntry);
    }
    return weekStat_;
  }

  public int getWeekStatCount() {
    return internalGetWeekStat().getMap().size();
  }
  /**
   * <code>map&lt;int32, int32&gt; weekStat = 3;</code>
   */

  @java.lang.Override
  public boolean containsWeekStat(
      int key) {
    
    return internalGetWeekStat().getMap().containsKey(key);
  }
  /**
   * Use {@link #getWeekStatMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.Integer, java.lang.Integer> getWeekStat() {
    return getWeekStatMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; weekStat = 3;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.Integer, java.lang.Integer> getWeekStatMap() {
    return internalGetWeekStat().getMap();
  }
  /**
   * <code>map&lt;int32, int32&gt; weekStat = 3;</code>
   */
  @java.lang.Override

  public int getWeekStatOrDefault(
      int key,
      int defaultValue) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetWeekStat().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;int32, int32&gt; weekStat = 3;</code>
   */
  @java.lang.Override

  public int getWeekStatOrThrow(
      int key) {
    
    java.util.Map<java.lang.Integer, java.lang.Integer> map =
        internalGetWeekStat().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int VISITSATWEEK_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.IntList visitsAtWeek_;
  /**
   * <code>repeated int32 visitsAtWeek = 4;</code>
   * @return A list containing the visitsAtWeek.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getVisitsAtWeekList() {
    return visitsAtWeek_;
  }
  /**
   * <code>repeated int32 visitsAtWeek = 4;</code>
   * @return The count of visitsAtWeek.
   */
  public int getVisitsAtWeekCount() {
    return visitsAtWeek_.size();
  }
  /**
   * <code>repeated int32 visitsAtWeek = 4;</code>
   * @param index The index of the element to return.
   * @return The visitsAtWeek at the given index.
   */
  public int getVisitsAtWeek(int index) {
    return visitsAtWeek_.getInt(index);
  }
  private int visitsAtWeekMemoizedSerializedSize = -1;

  public static final int VISITSDURATION_FIELD_NUMBER = 5;
  private com.google.protobuf.Internal.LongList visitsDuration_;
  /**
   * <code>repeated int64 visitsDuration = 5;</code>
   * @return A list containing the visitsDuration.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getVisitsDurationList() {
    return visitsDuration_;
  }
  /**
   * <code>repeated int64 visitsDuration = 5;</code>
   * @return The count of visitsDuration.
   */
  public int getVisitsDurationCount() {
    return visitsDuration_.size();
  }
  /**
   * <code>repeated int64 visitsDuration = 5;</code>
   * @param index The index of the element to return.
   * @return The visitsDuration at the given index.
   */
  public long getVisitsDuration(int index) {
    return visitsDuration_.getLong(index);
  }
  private int visitsDurationMemoizedSerializedSize = -1;

  public static final int PURCHASEDATE_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp purchaseDate_;
  /**
   * <code>.google.protobuf.Timestamp purchaseDate = 6;</code>
   * @return Whether the purchaseDate field is set.
   */
  @java.lang.Override
  public boolean hasPurchaseDate() {
    return purchaseDate_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp purchaseDate = 6;</code>
   * @return The purchaseDate.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getPurchaseDate() {
    return purchaseDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : purchaseDate_;
  }
  /**
   * <code>.google.protobuf.Timestamp purchaseDate = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getPurchaseDateOrBuilder() {
    return getPurchaseDate();
  }

  public static final int LASTENTER_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp lastEnter_;
  /**
   * <code>.google.protobuf.Timestamp lastEnter = 7;</code>
   * @return Whether the lastEnter field is set.
   */
  @java.lang.Override
  public boolean hasLastEnter() {
    return lastEnter_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp lastEnter = 7;</code>
   * @return The lastEnter.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getLastEnter() {
    return lastEnter_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastEnter_;
  }
  /**
   * <code>.google.protobuf.Timestamp lastEnter = 7;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getLastEnterOrBuilder() {
    return getLastEnter();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (userName_ != null) {
      output.writeMessage(2, getUserName());
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetWeekStat(),
        WeekStatDefaultEntryHolder.defaultEntry,
        3);
    if (getVisitsAtWeekList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(visitsAtWeekMemoizedSerializedSize);
    }
    for (int i = 0; i < visitsAtWeek_.size(); i++) {
      output.writeInt32NoTag(visitsAtWeek_.getInt(i));
    }
    if (getVisitsDurationList().size() > 0) {
      output.writeUInt32NoTag(42);
      output.writeUInt32NoTag(visitsDurationMemoizedSerializedSize);
    }
    for (int i = 0; i < visitsDuration_.size(); i++) {
      output.writeInt64NoTag(visitsDuration_.getLong(i));
    }
    if (purchaseDate_ != null) {
      output.writeMessage(6, getPurchaseDate());
    }
    if (lastEnter_ != null) {
      output.writeMessage(7, getLastEnter());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (userName_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUserName());
    }
    for (java.util.Map.Entry<java.lang.Integer, java.lang.Integer> entry
         : internalGetWeekStat().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
      weekStat__ = WeekStatDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, weekStat__);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < visitsAtWeek_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(visitsAtWeek_.getInt(i));
      }
      size += dataSize;
      if (!getVisitsAtWeekList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      visitsAtWeekMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      for (int i = 0; i < visitsDuration_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(visitsDuration_.getLong(i));
      }
      size += dataSize;
      if (!getVisitsDurationList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      visitsDurationMemoizedSerializedSize = dataSize;
    }
    if (purchaseDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getPurchaseDate());
    }
    if (lastEnter_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getLastEnter());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof me.mervap.message.GStat)) {
      return super.equals(obj);
    }
    me.mervap.message.GStat other = (me.mervap.message.GStat) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (hasUserName() != other.hasUserName()) return false;
    if (hasUserName()) {
      if (!getUserName()
          .equals(other.getUserName())) return false;
    }
    if (!internalGetWeekStat().equals(
        other.internalGetWeekStat())) return false;
    if (!getVisitsAtWeekList()
        .equals(other.getVisitsAtWeekList())) return false;
    if (!getVisitsDurationList()
        .equals(other.getVisitsDurationList())) return false;
    if (hasPurchaseDate() != other.hasPurchaseDate()) return false;
    if (hasPurchaseDate()) {
      if (!getPurchaseDate()
          .equals(other.getPurchaseDate())) return false;
    }
    if (hasLastEnter() != other.hasLastEnter()) return false;
    if (hasLastEnter()) {
      if (!getLastEnter()
          .equals(other.getLastEnter())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasUserName()) {
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
    }
    if (!internalGetWeekStat().getMap().isEmpty()) {
      hash = (37 * hash) + WEEKSTAT_FIELD_NUMBER;
      hash = (53 * hash) + internalGetWeekStat().hashCode();
    }
    if (getVisitsAtWeekCount() > 0) {
      hash = (37 * hash) + VISITSATWEEK_FIELD_NUMBER;
      hash = (53 * hash) + getVisitsAtWeekList().hashCode();
    }
    if (getVisitsDurationCount() > 0) {
      hash = (37 * hash) + VISITSDURATION_FIELD_NUMBER;
      hash = (53 * hash) + getVisitsDurationList().hashCode();
    }
    if (hasPurchaseDate()) {
      hash = (37 * hash) + PURCHASEDATE_FIELD_NUMBER;
      hash = (53 * hash) + getPurchaseDate().hashCode();
    }
    if (hasLastEnter()) {
      hash = (37 * hash) + LASTENTER_FIELD_NUMBER;
      hash = (53 * hash) + getLastEnter().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static me.mervap.message.GStat parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.mervap.message.GStat parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.mervap.message.GStat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.mervap.message.GStat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.mervap.message.GStat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.mervap.message.GStat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.mervap.message.GStat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.mervap.message.GStat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.mervap.message.GStat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static me.mervap.message.GStat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.mervap.message.GStat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.mervap.message.GStat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(me.mervap.message.GStat prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code me.mervap.GStat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:me.mervap.GStat)
      me.mervap.message.GStatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.mervap.message.Service.internal_static_me_mervap_GStat_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetWeekStat();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMutableWeekStat();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.mervap.message.Service.internal_static_me_mervap_GStat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.mervap.message.GStat.class, me.mervap.message.GStat.Builder.class);
    }

    // Construct using me.mervap.message.GStat.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      if (userNameBuilder_ == null) {
        userName_ = null;
      } else {
        userName_ = null;
        userNameBuilder_ = null;
      }
      internalGetMutableWeekStat().clear();
      visitsAtWeek_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      visitsDuration_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000004);
      if (purchaseDateBuilder_ == null) {
        purchaseDate_ = null;
      } else {
        purchaseDate_ = null;
        purchaseDateBuilder_ = null;
      }
      if (lastEnterBuilder_ == null) {
        lastEnter_ = null;
      } else {
        lastEnter_ = null;
        lastEnterBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return me.mervap.message.Service.internal_static_me_mervap_GStat_descriptor;
    }

    @java.lang.Override
    public me.mervap.message.GStat getDefaultInstanceForType() {
      return me.mervap.message.GStat.getDefaultInstance();
    }

    @java.lang.Override
    public me.mervap.message.GStat build() {
      me.mervap.message.GStat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public me.mervap.message.GStat buildPartial() {
      me.mervap.message.GStat result = new me.mervap.message.GStat(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      if (userNameBuilder_ == null) {
        result.userName_ = userName_;
      } else {
        result.userName_ = userNameBuilder_.build();
      }
      result.weekStat_ = internalGetWeekStat();
      result.weekStat_.makeImmutable();
      if (((bitField0_ & 0x00000002) != 0)) {
        visitsAtWeek_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.visitsAtWeek_ = visitsAtWeek_;
      if (((bitField0_ & 0x00000004) != 0)) {
        visitsDuration_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.visitsDuration_ = visitsDuration_;
      if (purchaseDateBuilder_ == null) {
        result.purchaseDate_ = purchaseDate_;
      } else {
        result.purchaseDate_ = purchaseDateBuilder_.build();
      }
      if (lastEnterBuilder_ == null) {
        result.lastEnter_ = lastEnter_;
      } else {
        result.lastEnter_ = lastEnterBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof me.mervap.message.GStat) {
        return mergeFrom((me.mervap.message.GStat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(me.mervap.message.GStat other) {
      if (other == me.mervap.message.GStat.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.hasUserName()) {
        mergeUserName(other.getUserName());
      }
      internalGetMutableWeekStat().mergeFrom(
          other.internalGetWeekStat());
      if (!other.visitsAtWeek_.isEmpty()) {
        if (visitsAtWeek_.isEmpty()) {
          visitsAtWeek_ = other.visitsAtWeek_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureVisitsAtWeekIsMutable();
          visitsAtWeek_.addAll(other.visitsAtWeek_);
        }
        onChanged();
      }
      if (!other.visitsDuration_.isEmpty()) {
        if (visitsDuration_.isEmpty()) {
          visitsDuration_ = other.visitsDuration_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureVisitsDurationIsMutable();
          visitsDuration_.addAll(other.visitsDuration_);
        }
        onChanged();
      }
      if (other.hasPurchaseDate()) {
        mergePurchaseDate(other.getPurchaseDate());
      }
      if (other.hasLastEnter()) {
        mergeLastEnter(other.getLastEnter());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      me.mervap.message.GStat parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (me.mervap.message.GStat) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private me.mervap.message.GUserName userName_;
    private com.google.protobuf.SingleFieldBuilderV3<
        me.mervap.message.GUserName, me.mervap.message.GUserName.Builder, me.mervap.message.GUserNameOrBuilder> userNameBuilder_;
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     * @return Whether the userName field is set.
     */
    public boolean hasUserName() {
      return userNameBuilder_ != null || userName_ != null;
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     * @return The userName.
     */
    public me.mervap.message.GUserName getUserName() {
      if (userNameBuilder_ == null) {
        return userName_ == null ? me.mervap.message.GUserName.getDefaultInstance() : userName_;
      } else {
        return userNameBuilder_.getMessage();
      }
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    public Builder setUserName(me.mervap.message.GUserName value) {
      if (userNameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userName_ = value;
        onChanged();
      } else {
        userNameBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    public Builder setUserName(
        me.mervap.message.GUserName.Builder builderForValue) {
      if (userNameBuilder_ == null) {
        userName_ = builderForValue.build();
        onChanged();
      } else {
        userNameBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    public Builder mergeUserName(me.mervap.message.GUserName value) {
      if (userNameBuilder_ == null) {
        if (userName_ != null) {
          userName_ =
            me.mervap.message.GUserName.newBuilder(userName_).mergeFrom(value).buildPartial();
        } else {
          userName_ = value;
        }
        onChanged();
      } else {
        userNameBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    public Builder clearUserName() {
      if (userNameBuilder_ == null) {
        userName_ = null;
        onChanged();
      } else {
        userName_ = null;
        userNameBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    public me.mervap.message.GUserName.Builder getUserNameBuilder() {
      
      onChanged();
      return getUserNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    public me.mervap.message.GUserNameOrBuilder getUserNameOrBuilder() {
      if (userNameBuilder_ != null) {
        return userNameBuilder_.getMessageOrBuilder();
      } else {
        return userName_ == null ?
            me.mervap.message.GUserName.getDefaultInstance() : userName_;
      }
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        me.mervap.message.GUserName, me.mervap.message.GUserName.Builder, me.mervap.message.GUserNameOrBuilder> 
        getUserNameFieldBuilder() {
      if (userNameBuilder_ == null) {
        userNameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            me.mervap.message.GUserName, me.mervap.message.GUserName.Builder, me.mervap.message.GUserNameOrBuilder>(
                getUserName(),
                getParentForChildren(),
                isClean());
        userName_ = null;
      }
      return userNameBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Integer> weekStat_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetWeekStat() {
      if (weekStat_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            WeekStatDefaultEntryHolder.defaultEntry);
      }
      return weekStat_;
    }
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetMutableWeekStat() {
      onChanged();;
      if (weekStat_ == null) {
        weekStat_ = com.google.protobuf.MapField.newMapField(
            WeekStatDefaultEntryHolder.defaultEntry);
      }
      if (!weekStat_.isMutable()) {
        weekStat_ = weekStat_.copy();
      }
      return weekStat_;
    }

    public int getWeekStatCount() {
      return internalGetWeekStat().getMap().size();
    }
    /**
     * <code>map&lt;int32, int32&gt; weekStat = 3;</code>
     */

    @java.lang.Override
    public boolean containsWeekStat(
        int key) {
      
      return internalGetWeekStat().getMap().containsKey(key);
    }
    /**
     * Use {@link #getWeekStatMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer> getWeekStat() {
      return getWeekStatMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; weekStat = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, java.lang.Integer> getWeekStatMap() {
      return internalGetWeekStat().getMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; weekStat = 3;</code>
     */
    @java.lang.Override

    public int getWeekStatOrDefault(
        int key,
        int defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetWeekStat().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, int32&gt; weekStat = 3;</code>
     */
    @java.lang.Override

    public int getWeekStatOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetWeekStat().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearWeekStat() {
      internalGetMutableWeekStat().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; weekStat = 3;</code>
     */

    public Builder removeWeekStat(
        int key) {
      
      internalGetMutableWeekStat().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer>
    getMutableWeekStat() {
      return internalGetMutableWeekStat().getMutableMap();
    }
    /**
     * <code>map&lt;int32, int32&gt; weekStat = 3;</code>
     */
    public Builder putWeekStat(
        int key,
        int value) {
      
      
      internalGetMutableWeekStat().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;int32, int32&gt; weekStat = 3;</code>
     */

    public Builder putAllWeekStat(
        java.util.Map<java.lang.Integer, java.lang.Integer> values) {
      internalGetMutableWeekStat().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.Internal.IntList visitsAtWeek_ = emptyIntList();
    private void ensureVisitsAtWeekIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        visitsAtWeek_ = mutableCopy(visitsAtWeek_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated int32 visitsAtWeek = 4;</code>
     * @return A list containing the visitsAtWeek.
     */
    public java.util.List<java.lang.Integer>
        getVisitsAtWeekList() {
      return ((bitField0_ & 0x00000002) != 0) ?
               java.util.Collections.unmodifiableList(visitsAtWeek_) : visitsAtWeek_;
    }
    /**
     * <code>repeated int32 visitsAtWeek = 4;</code>
     * @return The count of visitsAtWeek.
     */
    public int getVisitsAtWeekCount() {
      return visitsAtWeek_.size();
    }
    /**
     * <code>repeated int32 visitsAtWeek = 4;</code>
     * @param index The index of the element to return.
     * @return The visitsAtWeek at the given index.
     */
    public int getVisitsAtWeek(int index) {
      return visitsAtWeek_.getInt(index);
    }
    /**
     * <code>repeated int32 visitsAtWeek = 4;</code>
     * @param index The index to set the value at.
     * @param value The visitsAtWeek to set.
     * @return This builder for chaining.
     */
    public Builder setVisitsAtWeek(
        int index, int value) {
      ensureVisitsAtWeekIsMutable();
      visitsAtWeek_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 visitsAtWeek = 4;</code>
     * @param value The visitsAtWeek to add.
     * @return This builder for chaining.
     */
    public Builder addVisitsAtWeek(int value) {
      ensureVisitsAtWeekIsMutable();
      visitsAtWeek_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 visitsAtWeek = 4;</code>
     * @param values The visitsAtWeek to add.
     * @return This builder for chaining.
     */
    public Builder addAllVisitsAtWeek(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureVisitsAtWeekIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, visitsAtWeek_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 visitsAtWeek = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearVisitsAtWeek() {
      visitsAtWeek_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList visitsDuration_ = emptyLongList();
    private void ensureVisitsDurationIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        visitsDuration_ = mutableCopy(visitsDuration_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated int64 visitsDuration = 5;</code>
     * @return A list containing the visitsDuration.
     */
    public java.util.List<java.lang.Long>
        getVisitsDurationList() {
      return ((bitField0_ & 0x00000004) != 0) ?
               java.util.Collections.unmodifiableList(visitsDuration_) : visitsDuration_;
    }
    /**
     * <code>repeated int64 visitsDuration = 5;</code>
     * @return The count of visitsDuration.
     */
    public int getVisitsDurationCount() {
      return visitsDuration_.size();
    }
    /**
     * <code>repeated int64 visitsDuration = 5;</code>
     * @param index The index of the element to return.
     * @return The visitsDuration at the given index.
     */
    public long getVisitsDuration(int index) {
      return visitsDuration_.getLong(index);
    }
    /**
     * <code>repeated int64 visitsDuration = 5;</code>
     * @param index The index to set the value at.
     * @param value The visitsDuration to set.
     * @return This builder for chaining.
     */
    public Builder setVisitsDuration(
        int index, long value) {
      ensureVisitsDurationIsMutable();
      visitsDuration_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 visitsDuration = 5;</code>
     * @param value The visitsDuration to add.
     * @return This builder for chaining.
     */
    public Builder addVisitsDuration(long value) {
      ensureVisitsDurationIsMutable();
      visitsDuration_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 visitsDuration = 5;</code>
     * @param values The visitsDuration to add.
     * @return This builder for chaining.
     */
    public Builder addAllVisitsDuration(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureVisitsDurationIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, visitsDuration_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 visitsDuration = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearVisitsDuration() {
      visitsDuration_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp purchaseDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> purchaseDateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp purchaseDate = 6;</code>
     * @return Whether the purchaseDate field is set.
     */
    public boolean hasPurchaseDate() {
      return purchaseDateBuilder_ != null || purchaseDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp purchaseDate = 6;</code>
     * @return The purchaseDate.
     */
    public com.google.protobuf.Timestamp getPurchaseDate() {
      if (purchaseDateBuilder_ == null) {
        return purchaseDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : purchaseDate_;
      } else {
        return purchaseDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp purchaseDate = 6;</code>
     */
    public Builder setPurchaseDate(com.google.protobuf.Timestamp value) {
      if (purchaseDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        purchaseDate_ = value;
        onChanged();
      } else {
        purchaseDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp purchaseDate = 6;</code>
     */
    public Builder setPurchaseDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (purchaseDateBuilder_ == null) {
        purchaseDate_ = builderForValue.build();
        onChanged();
      } else {
        purchaseDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp purchaseDate = 6;</code>
     */
    public Builder mergePurchaseDate(com.google.protobuf.Timestamp value) {
      if (purchaseDateBuilder_ == null) {
        if (purchaseDate_ != null) {
          purchaseDate_ =
            com.google.protobuf.Timestamp.newBuilder(purchaseDate_).mergeFrom(value).buildPartial();
        } else {
          purchaseDate_ = value;
        }
        onChanged();
      } else {
        purchaseDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp purchaseDate = 6;</code>
     */
    public Builder clearPurchaseDate() {
      if (purchaseDateBuilder_ == null) {
        purchaseDate_ = null;
        onChanged();
      } else {
        purchaseDate_ = null;
        purchaseDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp purchaseDate = 6;</code>
     */
    public com.google.protobuf.Timestamp.Builder getPurchaseDateBuilder() {
      
      onChanged();
      return getPurchaseDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp purchaseDate = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getPurchaseDateOrBuilder() {
      if (purchaseDateBuilder_ != null) {
        return purchaseDateBuilder_.getMessageOrBuilder();
      } else {
        return purchaseDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : purchaseDate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp purchaseDate = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getPurchaseDateFieldBuilder() {
      if (purchaseDateBuilder_ == null) {
        purchaseDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getPurchaseDate(),
                getParentForChildren(),
                isClean());
        purchaseDate_ = null;
      }
      return purchaseDateBuilder_;
    }

    private com.google.protobuf.Timestamp lastEnter_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastEnterBuilder_;
    /**
     * <code>.google.protobuf.Timestamp lastEnter = 7;</code>
     * @return Whether the lastEnter field is set.
     */
    public boolean hasLastEnter() {
      return lastEnterBuilder_ != null || lastEnter_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp lastEnter = 7;</code>
     * @return The lastEnter.
     */
    public com.google.protobuf.Timestamp getLastEnter() {
      if (lastEnterBuilder_ == null) {
        return lastEnter_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastEnter_;
      } else {
        return lastEnterBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp lastEnter = 7;</code>
     */
    public Builder setLastEnter(com.google.protobuf.Timestamp value) {
      if (lastEnterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastEnter_ = value;
        onChanged();
      } else {
        lastEnterBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lastEnter = 7;</code>
     */
    public Builder setLastEnter(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (lastEnterBuilder_ == null) {
        lastEnter_ = builderForValue.build();
        onChanged();
      } else {
        lastEnterBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lastEnter = 7;</code>
     */
    public Builder mergeLastEnter(com.google.protobuf.Timestamp value) {
      if (lastEnterBuilder_ == null) {
        if (lastEnter_ != null) {
          lastEnter_ =
            com.google.protobuf.Timestamp.newBuilder(lastEnter_).mergeFrom(value).buildPartial();
        } else {
          lastEnter_ = value;
        }
        onChanged();
      } else {
        lastEnterBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lastEnter = 7;</code>
     */
    public Builder clearLastEnter() {
      if (lastEnterBuilder_ == null) {
        lastEnter_ = null;
        onChanged();
      } else {
        lastEnter_ = null;
        lastEnterBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lastEnter = 7;</code>
     */
    public com.google.protobuf.Timestamp.Builder getLastEnterBuilder() {
      
      onChanged();
      return getLastEnterFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp lastEnter = 7;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLastEnterOrBuilder() {
      if (lastEnterBuilder_ != null) {
        return lastEnterBuilder_.getMessageOrBuilder();
      } else {
        return lastEnter_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : lastEnter_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp lastEnter = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getLastEnterFieldBuilder() {
      if (lastEnterBuilder_ == null) {
        lastEnterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getLastEnter(),
                getParentForChildren(),
                isClean());
        lastEnter_ = null;
      }
      return lastEnterBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:me.mervap.GStat)
  }

  // @@protoc_insertion_point(class_scope:me.mervap.GStat)
  private static final me.mervap.message.GStat DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new me.mervap.message.GStat();
  }

  public static me.mervap.message.GStat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GStat>
      PARSER = new com.google.protobuf.AbstractParser<GStat>() {
    @java.lang.Override
    public GStat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GStat(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GStat> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GStat> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public me.mervap.message.GStat getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

