// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package me.mervap.message;

public interface GSubscriptionInfoListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.mervap.GSubscriptionInfoList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
   */
  java.util.List<me.mervap.message.GSubscriptionInfo> 
      getInfosList();
  /**
   * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
   */
  me.mervap.message.GSubscriptionInfo getInfos(int index);
  /**
   * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
   */
  int getInfosCount();
  /**
   * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
   */
  java.util.List<? extends me.mervap.message.GSubscriptionInfoOrBuilder> 
      getInfosOrBuilderList();
  /**
   * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
   */
  me.mervap.message.GSubscriptionInfoOrBuilder getInfosOrBuilder(
      int index);
}
