// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package me.mervap.message;

/**
 * Protobuf type {@code me.mervap.GSubscriptionInfoList}
 */
public final class GSubscriptionInfoList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:me.mervap.GSubscriptionInfoList)
    GSubscriptionInfoListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GSubscriptionInfoList.newBuilder() to construct.
  private GSubscriptionInfoList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GSubscriptionInfoList() {
    infos_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GSubscriptionInfoList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GSubscriptionInfoList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              infos_ = new java.util.ArrayList<me.mervap.message.GSubscriptionInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            infos_.add(
                input.readMessage(me.mervap.message.GSubscriptionInfo.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        infos_ = java.util.Collections.unmodifiableList(infos_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return me.mervap.message.Service.internal_static_me_mervap_GSubscriptionInfoList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return me.mervap.message.Service.internal_static_me_mervap_GSubscriptionInfoList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            me.mervap.message.GSubscriptionInfoList.class, me.mervap.message.GSubscriptionInfoList.Builder.class);
  }

  public static final int INFOS_FIELD_NUMBER = 1;
  private java.util.List<me.mervap.message.GSubscriptionInfo> infos_;
  /**
   * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
   */
  @java.lang.Override
  public java.util.List<me.mervap.message.GSubscriptionInfo> getInfosList() {
    return infos_;
  }
  /**
   * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends me.mervap.message.GSubscriptionInfoOrBuilder> 
      getInfosOrBuilderList() {
    return infos_;
  }
  /**
   * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
   */
  @java.lang.Override
  public int getInfosCount() {
    return infos_.size();
  }
  /**
   * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
   */
  @java.lang.Override
  public me.mervap.message.GSubscriptionInfo getInfos(int index) {
    return infos_.get(index);
  }
  /**
   * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
   */
  @java.lang.Override
  public me.mervap.message.GSubscriptionInfoOrBuilder getInfosOrBuilder(
      int index) {
    return infos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < infos_.size(); i++) {
      output.writeMessage(1, infos_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < infos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, infos_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof me.mervap.message.GSubscriptionInfoList)) {
      return super.equals(obj);
    }
    me.mervap.message.GSubscriptionInfoList other = (me.mervap.message.GSubscriptionInfoList) obj;

    if (!getInfosList()
        .equals(other.getInfosList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getInfosCount() > 0) {
      hash = (37 * hash) + INFOS_FIELD_NUMBER;
      hash = (53 * hash) + getInfosList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static me.mervap.message.GSubscriptionInfoList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.mervap.message.GSubscriptionInfoList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.mervap.message.GSubscriptionInfoList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.mervap.message.GSubscriptionInfoList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.mervap.message.GSubscriptionInfoList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.mervap.message.GSubscriptionInfoList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.mervap.message.GSubscriptionInfoList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.mervap.message.GSubscriptionInfoList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.mervap.message.GSubscriptionInfoList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static me.mervap.message.GSubscriptionInfoList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.mervap.message.GSubscriptionInfoList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.mervap.message.GSubscriptionInfoList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(me.mervap.message.GSubscriptionInfoList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code me.mervap.GSubscriptionInfoList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:me.mervap.GSubscriptionInfoList)
      me.mervap.message.GSubscriptionInfoListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.mervap.message.Service.internal_static_me_mervap_GSubscriptionInfoList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.mervap.message.Service.internal_static_me_mervap_GSubscriptionInfoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.mervap.message.GSubscriptionInfoList.class, me.mervap.message.GSubscriptionInfoList.Builder.class);
    }

    // Construct using me.mervap.message.GSubscriptionInfoList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getInfosFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (infosBuilder_ == null) {
        infos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        infosBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return me.mervap.message.Service.internal_static_me_mervap_GSubscriptionInfoList_descriptor;
    }

    @java.lang.Override
    public me.mervap.message.GSubscriptionInfoList getDefaultInstanceForType() {
      return me.mervap.message.GSubscriptionInfoList.getDefaultInstance();
    }

    @java.lang.Override
    public me.mervap.message.GSubscriptionInfoList build() {
      me.mervap.message.GSubscriptionInfoList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public me.mervap.message.GSubscriptionInfoList buildPartial() {
      me.mervap.message.GSubscriptionInfoList result = new me.mervap.message.GSubscriptionInfoList(this);
      int from_bitField0_ = bitField0_;
      if (infosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          infos_ = java.util.Collections.unmodifiableList(infos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.infos_ = infos_;
      } else {
        result.infos_ = infosBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof me.mervap.message.GSubscriptionInfoList) {
        return mergeFrom((me.mervap.message.GSubscriptionInfoList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(me.mervap.message.GSubscriptionInfoList other) {
      if (other == me.mervap.message.GSubscriptionInfoList.getDefaultInstance()) return this;
      if (infosBuilder_ == null) {
        if (!other.infos_.isEmpty()) {
          if (infos_.isEmpty()) {
            infos_ = other.infos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInfosIsMutable();
            infos_.addAll(other.infos_);
          }
          onChanged();
        }
      } else {
        if (!other.infos_.isEmpty()) {
          if (infosBuilder_.isEmpty()) {
            infosBuilder_.dispose();
            infosBuilder_ = null;
            infos_ = other.infos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            infosBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInfosFieldBuilder() : null;
          } else {
            infosBuilder_.addAllMessages(other.infos_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      me.mervap.message.GSubscriptionInfoList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (me.mervap.message.GSubscriptionInfoList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<me.mervap.message.GSubscriptionInfo> infos_ =
      java.util.Collections.emptyList();
    private void ensureInfosIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        infos_ = new java.util.ArrayList<me.mervap.message.GSubscriptionInfo>(infos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        me.mervap.message.GSubscriptionInfo, me.mervap.message.GSubscriptionInfo.Builder, me.mervap.message.GSubscriptionInfoOrBuilder> infosBuilder_;

    /**
     * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
     */
    public java.util.List<me.mervap.message.GSubscriptionInfo> getInfosList() {
      if (infosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(infos_);
      } else {
        return infosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
     */
    public int getInfosCount() {
      if (infosBuilder_ == null) {
        return infos_.size();
      } else {
        return infosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
     */
    public me.mervap.message.GSubscriptionInfo getInfos(int index) {
      if (infosBuilder_ == null) {
        return infos_.get(index);
      } else {
        return infosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
     */
    public Builder setInfos(
        int index, me.mervap.message.GSubscriptionInfo value) {
      if (infosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInfosIsMutable();
        infos_.set(index, value);
        onChanged();
      } else {
        infosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
     */
    public Builder setInfos(
        int index, me.mervap.message.GSubscriptionInfo.Builder builderForValue) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        infos_.set(index, builderForValue.build());
        onChanged();
      } else {
        infosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
     */
    public Builder addInfos(me.mervap.message.GSubscriptionInfo value) {
      if (infosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInfosIsMutable();
        infos_.add(value);
        onChanged();
      } else {
        infosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
     */
    public Builder addInfos(
        int index, me.mervap.message.GSubscriptionInfo value) {
      if (infosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInfosIsMutable();
        infos_.add(index, value);
        onChanged();
      } else {
        infosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
     */
    public Builder addInfos(
        me.mervap.message.GSubscriptionInfo.Builder builderForValue) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        infos_.add(builderForValue.build());
        onChanged();
      } else {
        infosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
     */
    public Builder addInfos(
        int index, me.mervap.message.GSubscriptionInfo.Builder builderForValue) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        infos_.add(index, builderForValue.build());
        onChanged();
      } else {
        infosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
     */
    public Builder addAllInfos(
        java.lang.Iterable<? extends me.mervap.message.GSubscriptionInfo> values) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, infos_);
        onChanged();
      } else {
        infosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
     */
    public Builder clearInfos() {
      if (infosBuilder_ == null) {
        infos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        infosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
     */
    public Builder removeInfos(int index) {
      if (infosBuilder_ == null) {
        ensureInfosIsMutable();
        infos_.remove(index);
        onChanged();
      } else {
        infosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
     */
    public me.mervap.message.GSubscriptionInfo.Builder getInfosBuilder(
        int index) {
      return getInfosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
     */
    public me.mervap.message.GSubscriptionInfoOrBuilder getInfosOrBuilder(
        int index) {
      if (infosBuilder_ == null) {
        return infos_.get(index);  } else {
        return infosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
     */
    public java.util.List<? extends me.mervap.message.GSubscriptionInfoOrBuilder> 
         getInfosOrBuilderList() {
      if (infosBuilder_ != null) {
        return infosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(infos_);
      }
    }
    /**
     * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
     */
    public me.mervap.message.GSubscriptionInfo.Builder addInfosBuilder() {
      return getInfosFieldBuilder().addBuilder(
          me.mervap.message.GSubscriptionInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
     */
    public me.mervap.message.GSubscriptionInfo.Builder addInfosBuilder(
        int index) {
      return getInfosFieldBuilder().addBuilder(
          index, me.mervap.message.GSubscriptionInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .me.mervap.GSubscriptionInfo infos = 1;</code>
     */
    public java.util.List<me.mervap.message.GSubscriptionInfo.Builder> 
         getInfosBuilderList() {
      return getInfosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        me.mervap.message.GSubscriptionInfo, me.mervap.message.GSubscriptionInfo.Builder, me.mervap.message.GSubscriptionInfoOrBuilder> 
        getInfosFieldBuilder() {
      if (infosBuilder_ == null) {
        infosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            me.mervap.message.GSubscriptionInfo, me.mervap.message.GSubscriptionInfo.Builder, me.mervap.message.GSubscriptionInfoOrBuilder>(
                infos_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        infos_ = null;
      }
      return infosBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:me.mervap.GSubscriptionInfoList)
  }

  // @@protoc_insertion_point(class_scope:me.mervap.GSubscriptionInfoList)
  private static final me.mervap.message.GSubscriptionInfoList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new me.mervap.message.GSubscriptionInfoList();
  }

  public static me.mervap.message.GSubscriptionInfoList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GSubscriptionInfoList>
      PARSER = new com.google.protobuf.AbstractParser<GSubscriptionInfoList>() {
    @java.lang.Override
    public GSubscriptionInfoList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GSubscriptionInfoList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GSubscriptionInfoList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GSubscriptionInfoList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public me.mervap.message.GSubscriptionInfoList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

