// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package me.mervap.message;

public interface GSubscriptionInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.mervap.GSubscriptionInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.me.mervap.GUserName userName = 2;</code>
   * @return Whether the userName field is set.
   */
  boolean hasUserName();
  /**
   * <code>.me.mervap.GUserName userName = 2;</code>
   * @return The userName.
   */
  me.mervap.message.GUserName getUserName();
  /**
   * <code>.me.mervap.GUserName userName = 2;</code>
   */
  me.mervap.message.GUserNameOrBuilder getUserNameOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp expireDate = 3;</code>
   * @return Whether the expireDate field is set.
   */
  boolean hasExpireDate();
  /**
   * <code>.google.protobuf.Timestamp expireDate = 3;</code>
   * @return The expireDate.
   */
  com.google.protobuf.Timestamp getExpireDate();
  /**
   * <code>.google.protobuf.Timestamp expireDate = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getExpireDateOrBuilder();
}
