// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package me.mervap.message;

/**
 * Protobuf type {@code me.mervap.GSubscriptionInfo}
 */
public final class GSubscriptionInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:me.mervap.GSubscriptionInfo)
    GSubscriptionInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GSubscriptionInfo.newBuilder() to construct.
  private GSubscriptionInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GSubscriptionInfo() {
    id_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GSubscriptionInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GSubscriptionInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            me.mervap.message.GUserName.Builder subBuilder = null;
            if (userName_ != null) {
              subBuilder = userName_.toBuilder();
            }
            userName_ = input.readMessage(me.mervap.message.GUserName.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(userName_);
              userName_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (expireDate_ != null) {
              subBuilder = expireDate_.toBuilder();
            }
            expireDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(expireDate_);
              expireDate_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return me.mervap.message.Service.internal_static_me_mervap_GSubscriptionInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return me.mervap.message.Service.internal_static_me_mervap_GSubscriptionInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            me.mervap.message.GSubscriptionInfo.class, me.mervap.message.GSubscriptionInfo.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  private me.mervap.message.GUserName userName_;
  /**
   * <code>.me.mervap.GUserName userName = 2;</code>
   * @return Whether the userName field is set.
   */
  @java.lang.Override
  public boolean hasUserName() {
    return userName_ != null;
  }
  /**
   * <code>.me.mervap.GUserName userName = 2;</code>
   * @return The userName.
   */
  @java.lang.Override
  public me.mervap.message.GUserName getUserName() {
    return userName_ == null ? me.mervap.message.GUserName.getDefaultInstance() : userName_;
  }
  /**
   * <code>.me.mervap.GUserName userName = 2;</code>
   */
  @java.lang.Override
  public me.mervap.message.GUserNameOrBuilder getUserNameOrBuilder() {
    return getUserName();
  }

  public static final int EXPIREDATE_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp expireDate_;
  /**
   * <code>.google.protobuf.Timestamp expireDate = 3;</code>
   * @return Whether the expireDate field is set.
   */
  @java.lang.Override
  public boolean hasExpireDate() {
    return expireDate_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp expireDate = 3;</code>
   * @return The expireDate.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getExpireDate() {
    return expireDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expireDate_;
  }
  /**
   * <code>.google.protobuf.Timestamp expireDate = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getExpireDateOrBuilder() {
    return getExpireDate();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (userName_ != null) {
      output.writeMessage(2, getUserName());
    }
    if (expireDate_ != null) {
      output.writeMessage(3, getExpireDate());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (userName_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUserName());
    }
    if (expireDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getExpireDate());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof me.mervap.message.GSubscriptionInfo)) {
      return super.equals(obj);
    }
    me.mervap.message.GSubscriptionInfo other = (me.mervap.message.GSubscriptionInfo) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (hasUserName() != other.hasUserName()) return false;
    if (hasUserName()) {
      if (!getUserName()
          .equals(other.getUserName())) return false;
    }
    if (hasExpireDate() != other.hasExpireDate()) return false;
    if (hasExpireDate()) {
      if (!getExpireDate()
          .equals(other.getExpireDate())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasUserName()) {
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
    }
    if (hasExpireDate()) {
      hash = (37 * hash) + EXPIREDATE_FIELD_NUMBER;
      hash = (53 * hash) + getExpireDate().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static me.mervap.message.GSubscriptionInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.mervap.message.GSubscriptionInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.mervap.message.GSubscriptionInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.mervap.message.GSubscriptionInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.mervap.message.GSubscriptionInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.mervap.message.GSubscriptionInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.mervap.message.GSubscriptionInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.mervap.message.GSubscriptionInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.mervap.message.GSubscriptionInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static me.mervap.message.GSubscriptionInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.mervap.message.GSubscriptionInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.mervap.message.GSubscriptionInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(me.mervap.message.GSubscriptionInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code me.mervap.GSubscriptionInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:me.mervap.GSubscriptionInfo)
      me.mervap.message.GSubscriptionInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.mervap.message.Service.internal_static_me_mervap_GSubscriptionInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.mervap.message.Service.internal_static_me_mervap_GSubscriptionInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.mervap.message.GSubscriptionInfo.class, me.mervap.message.GSubscriptionInfo.Builder.class);
    }

    // Construct using me.mervap.message.GSubscriptionInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      if (userNameBuilder_ == null) {
        userName_ = null;
      } else {
        userName_ = null;
        userNameBuilder_ = null;
      }
      if (expireDateBuilder_ == null) {
        expireDate_ = null;
      } else {
        expireDate_ = null;
        expireDateBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return me.mervap.message.Service.internal_static_me_mervap_GSubscriptionInfo_descriptor;
    }

    @java.lang.Override
    public me.mervap.message.GSubscriptionInfo getDefaultInstanceForType() {
      return me.mervap.message.GSubscriptionInfo.getDefaultInstance();
    }

    @java.lang.Override
    public me.mervap.message.GSubscriptionInfo build() {
      me.mervap.message.GSubscriptionInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public me.mervap.message.GSubscriptionInfo buildPartial() {
      me.mervap.message.GSubscriptionInfo result = new me.mervap.message.GSubscriptionInfo(this);
      result.id_ = id_;
      if (userNameBuilder_ == null) {
        result.userName_ = userName_;
      } else {
        result.userName_ = userNameBuilder_.build();
      }
      if (expireDateBuilder_ == null) {
        result.expireDate_ = expireDate_;
      } else {
        result.expireDate_ = expireDateBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof me.mervap.message.GSubscriptionInfo) {
        return mergeFrom((me.mervap.message.GSubscriptionInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(me.mervap.message.GSubscriptionInfo other) {
      if (other == me.mervap.message.GSubscriptionInfo.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.hasUserName()) {
        mergeUserName(other.getUserName());
      }
      if (other.hasExpireDate()) {
        mergeExpireDate(other.getExpireDate());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      me.mervap.message.GSubscriptionInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (me.mervap.message.GSubscriptionInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private me.mervap.message.GUserName userName_;
    private com.google.protobuf.SingleFieldBuilderV3<
        me.mervap.message.GUserName, me.mervap.message.GUserName.Builder, me.mervap.message.GUserNameOrBuilder> userNameBuilder_;
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     * @return Whether the userName field is set.
     */
    public boolean hasUserName() {
      return userNameBuilder_ != null || userName_ != null;
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     * @return The userName.
     */
    public me.mervap.message.GUserName getUserName() {
      if (userNameBuilder_ == null) {
        return userName_ == null ? me.mervap.message.GUserName.getDefaultInstance() : userName_;
      } else {
        return userNameBuilder_.getMessage();
      }
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    public Builder setUserName(me.mervap.message.GUserName value) {
      if (userNameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userName_ = value;
        onChanged();
      } else {
        userNameBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    public Builder setUserName(
        me.mervap.message.GUserName.Builder builderForValue) {
      if (userNameBuilder_ == null) {
        userName_ = builderForValue.build();
        onChanged();
      } else {
        userNameBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    public Builder mergeUserName(me.mervap.message.GUserName value) {
      if (userNameBuilder_ == null) {
        if (userName_ != null) {
          userName_ =
            me.mervap.message.GUserName.newBuilder(userName_).mergeFrom(value).buildPartial();
        } else {
          userName_ = value;
        }
        onChanged();
      } else {
        userNameBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    public Builder clearUserName() {
      if (userNameBuilder_ == null) {
        userName_ = null;
        onChanged();
      } else {
        userName_ = null;
        userNameBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    public me.mervap.message.GUserName.Builder getUserNameBuilder() {
      
      onChanged();
      return getUserNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    public me.mervap.message.GUserNameOrBuilder getUserNameOrBuilder() {
      if (userNameBuilder_ != null) {
        return userNameBuilder_.getMessageOrBuilder();
      } else {
        return userName_ == null ?
            me.mervap.message.GUserName.getDefaultInstance() : userName_;
      }
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        me.mervap.message.GUserName, me.mervap.message.GUserName.Builder, me.mervap.message.GUserNameOrBuilder> 
        getUserNameFieldBuilder() {
      if (userNameBuilder_ == null) {
        userNameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            me.mervap.message.GUserName, me.mervap.message.GUserName.Builder, me.mervap.message.GUserNameOrBuilder>(
                getUserName(),
                getParentForChildren(),
                isClean());
        userName_ = null;
      }
      return userNameBuilder_;
    }

    private com.google.protobuf.Timestamp expireDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> expireDateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp expireDate = 3;</code>
     * @return Whether the expireDate field is set.
     */
    public boolean hasExpireDate() {
      return expireDateBuilder_ != null || expireDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp expireDate = 3;</code>
     * @return The expireDate.
     */
    public com.google.protobuf.Timestamp getExpireDate() {
      if (expireDateBuilder_ == null) {
        return expireDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expireDate_;
      } else {
        return expireDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp expireDate = 3;</code>
     */
    public Builder setExpireDate(com.google.protobuf.Timestamp value) {
      if (expireDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expireDate_ = value;
        onChanged();
      } else {
        expireDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expireDate = 3;</code>
     */
    public Builder setExpireDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (expireDateBuilder_ == null) {
        expireDate_ = builderForValue.build();
        onChanged();
      } else {
        expireDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expireDate = 3;</code>
     */
    public Builder mergeExpireDate(com.google.protobuf.Timestamp value) {
      if (expireDateBuilder_ == null) {
        if (expireDate_ != null) {
          expireDate_ =
            com.google.protobuf.Timestamp.newBuilder(expireDate_).mergeFrom(value).buildPartial();
        } else {
          expireDate_ = value;
        }
        onChanged();
      } else {
        expireDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expireDate = 3;</code>
     */
    public Builder clearExpireDate() {
      if (expireDateBuilder_ == null) {
        expireDate_ = null;
        onChanged();
      } else {
        expireDate_ = null;
        expireDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expireDate = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getExpireDateBuilder() {
      
      onChanged();
      return getExpireDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp expireDate = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getExpireDateOrBuilder() {
      if (expireDateBuilder_ != null) {
        return expireDateBuilder_.getMessageOrBuilder();
      } else {
        return expireDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : expireDate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp expireDate = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getExpireDateFieldBuilder() {
      if (expireDateBuilder_ == null) {
        expireDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getExpireDate(),
                getParentForChildren(),
                isClean());
        expireDate_ = null;
      }
      return expireDateBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:me.mervap.GSubscriptionInfo)
  }

  // @@protoc_insertion_point(class_scope:me.mervap.GSubscriptionInfo)
  private static final me.mervap.message.GSubscriptionInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new me.mervap.message.GSubscriptionInfo();
  }

  public static me.mervap.message.GSubscriptionInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GSubscriptionInfo>
      PARSER = new com.google.protobuf.AbstractParser<GSubscriptionInfo>() {
    @java.lang.Override
    public GSubscriptionInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GSubscriptionInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GSubscriptionInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GSubscriptionInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public me.mervap.message.GSubscriptionInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

