// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package me.mervap.message;

public interface GUpdateSubscriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:me.mervap.GUpdateSubscription)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.me.mervap.GUserName userName = 2;</code>
   * @return Whether the userName field is set.
   */
  boolean hasUserName();
  /**
   * <code>.me.mervap.GUserName userName = 2;</code>
   * @return The userName.
   */
  me.mervap.message.GUserName getUserName();
  /**
   * <code>.me.mervap.GUserName userName = 2;</code>
   */
  me.mervap.message.GUserNameOrBuilder getUserNameOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp purchaseDate = 3;</code>
   * @return Whether the purchaseDate field is set.
   */
  boolean hasPurchaseDate();
  /**
   * <code>.google.protobuf.Timestamp purchaseDate = 3;</code>
   * @return The purchaseDate.
   */
  com.google.protobuf.Timestamp getPurchaseDate();
  /**
   * <code>.google.protobuf.Timestamp purchaseDate = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getPurchaseDateOrBuilder();

  /**
   * <code>.me.mervap.GPeriod period = 4;</code>
   * @return The enum numeric value on the wire for period.
   */
  int getPeriodValue();
  /**
   * <code>.me.mervap.GPeriod period = 4;</code>
   * @return The period.
   */
  me.mervap.message.GPeriod getPeriod();
}
