// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package me.mervap.message;

/**
 * Protobuf type {@code me.mervap.GUpdateSubscription}
 */
public final class GUpdateSubscription extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:me.mervap.GUpdateSubscription)
    GUpdateSubscriptionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GUpdateSubscription.newBuilder() to construct.
  private GUpdateSubscription(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GUpdateSubscription() {
    id_ = "";
    period_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GUpdateSubscription();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GUpdateSubscription(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            me.mervap.message.GUserName.Builder subBuilder = null;
            if (userName_ != null) {
              subBuilder = userName_.toBuilder();
            }
            userName_ = input.readMessage(me.mervap.message.GUserName.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(userName_);
              userName_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (purchaseDate_ != null) {
              subBuilder = purchaseDate_.toBuilder();
            }
            purchaseDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(purchaseDate_);
              purchaseDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            period_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return me.mervap.message.Service.internal_static_me_mervap_GUpdateSubscription_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return me.mervap.message.Service.internal_static_me_mervap_GUpdateSubscription_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            me.mervap.message.GUpdateSubscription.class, me.mervap.message.GUpdateSubscription.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  private me.mervap.message.GUserName userName_;
  /**
   * <code>.me.mervap.GUserName userName = 2;</code>
   * @return Whether the userName field is set.
   */
  @java.lang.Override
  public boolean hasUserName() {
    return userName_ != null;
  }
  /**
   * <code>.me.mervap.GUserName userName = 2;</code>
   * @return The userName.
   */
  @java.lang.Override
  public me.mervap.message.GUserName getUserName() {
    return userName_ == null ? me.mervap.message.GUserName.getDefaultInstance() : userName_;
  }
  /**
   * <code>.me.mervap.GUserName userName = 2;</code>
   */
  @java.lang.Override
  public me.mervap.message.GUserNameOrBuilder getUserNameOrBuilder() {
    return getUserName();
  }

  public static final int PURCHASEDATE_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp purchaseDate_;
  /**
   * <code>.google.protobuf.Timestamp purchaseDate = 3;</code>
   * @return Whether the purchaseDate field is set.
   */
  @java.lang.Override
  public boolean hasPurchaseDate() {
    return purchaseDate_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp purchaseDate = 3;</code>
   * @return The purchaseDate.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getPurchaseDate() {
    return purchaseDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : purchaseDate_;
  }
  /**
   * <code>.google.protobuf.Timestamp purchaseDate = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getPurchaseDateOrBuilder() {
    return getPurchaseDate();
  }

  public static final int PERIOD_FIELD_NUMBER = 4;
  private int period_;
  /**
   * <code>.me.mervap.GPeriod period = 4;</code>
   * @return The enum numeric value on the wire for period.
   */
  @java.lang.Override public int getPeriodValue() {
    return period_;
  }
  /**
   * <code>.me.mervap.GPeriod period = 4;</code>
   * @return The period.
   */
  @java.lang.Override public me.mervap.message.GPeriod getPeriod() {
    @SuppressWarnings("deprecation")
    me.mervap.message.GPeriod result = me.mervap.message.GPeriod.valueOf(period_);
    return result == null ? me.mervap.message.GPeriod.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (userName_ != null) {
      output.writeMessage(2, getUserName());
    }
    if (purchaseDate_ != null) {
      output.writeMessage(3, getPurchaseDate());
    }
    if (period_ != me.mervap.message.GPeriod.DAY.getNumber()) {
      output.writeEnum(4, period_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (userName_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUserName());
    }
    if (purchaseDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPurchaseDate());
    }
    if (period_ != me.mervap.message.GPeriod.DAY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, period_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof me.mervap.message.GUpdateSubscription)) {
      return super.equals(obj);
    }
    me.mervap.message.GUpdateSubscription other = (me.mervap.message.GUpdateSubscription) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (hasUserName() != other.hasUserName()) return false;
    if (hasUserName()) {
      if (!getUserName()
          .equals(other.getUserName())) return false;
    }
    if (hasPurchaseDate() != other.hasPurchaseDate()) return false;
    if (hasPurchaseDate()) {
      if (!getPurchaseDate()
          .equals(other.getPurchaseDate())) return false;
    }
    if (period_ != other.period_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasUserName()) {
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
    }
    if (hasPurchaseDate()) {
      hash = (37 * hash) + PURCHASEDATE_FIELD_NUMBER;
      hash = (53 * hash) + getPurchaseDate().hashCode();
    }
    hash = (37 * hash) + PERIOD_FIELD_NUMBER;
    hash = (53 * hash) + period_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static me.mervap.message.GUpdateSubscription parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.mervap.message.GUpdateSubscription parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.mervap.message.GUpdateSubscription parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.mervap.message.GUpdateSubscription parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.mervap.message.GUpdateSubscription parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static me.mervap.message.GUpdateSubscription parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static me.mervap.message.GUpdateSubscription parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.mervap.message.GUpdateSubscription parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.mervap.message.GUpdateSubscription parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static me.mervap.message.GUpdateSubscription parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static me.mervap.message.GUpdateSubscription parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static me.mervap.message.GUpdateSubscription parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(me.mervap.message.GUpdateSubscription prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code me.mervap.GUpdateSubscription}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:me.mervap.GUpdateSubscription)
      me.mervap.message.GUpdateSubscriptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.mervap.message.Service.internal_static_me_mervap_GUpdateSubscription_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.mervap.message.Service.internal_static_me_mervap_GUpdateSubscription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.mervap.message.GUpdateSubscription.class, me.mervap.message.GUpdateSubscription.Builder.class);
    }

    // Construct using me.mervap.message.GUpdateSubscription.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      if (userNameBuilder_ == null) {
        userName_ = null;
      } else {
        userName_ = null;
        userNameBuilder_ = null;
      }
      if (purchaseDateBuilder_ == null) {
        purchaseDate_ = null;
      } else {
        purchaseDate_ = null;
        purchaseDateBuilder_ = null;
      }
      period_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return me.mervap.message.Service.internal_static_me_mervap_GUpdateSubscription_descriptor;
    }

    @java.lang.Override
    public me.mervap.message.GUpdateSubscription getDefaultInstanceForType() {
      return me.mervap.message.GUpdateSubscription.getDefaultInstance();
    }

    @java.lang.Override
    public me.mervap.message.GUpdateSubscription build() {
      me.mervap.message.GUpdateSubscription result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public me.mervap.message.GUpdateSubscription buildPartial() {
      me.mervap.message.GUpdateSubscription result = new me.mervap.message.GUpdateSubscription(this);
      result.id_ = id_;
      if (userNameBuilder_ == null) {
        result.userName_ = userName_;
      } else {
        result.userName_ = userNameBuilder_.build();
      }
      if (purchaseDateBuilder_ == null) {
        result.purchaseDate_ = purchaseDate_;
      } else {
        result.purchaseDate_ = purchaseDateBuilder_.build();
      }
      result.period_ = period_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof me.mervap.message.GUpdateSubscription) {
        return mergeFrom((me.mervap.message.GUpdateSubscription)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(me.mervap.message.GUpdateSubscription other) {
      if (other == me.mervap.message.GUpdateSubscription.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.hasUserName()) {
        mergeUserName(other.getUserName());
      }
      if (other.hasPurchaseDate()) {
        mergePurchaseDate(other.getPurchaseDate());
      }
      if (other.period_ != 0) {
        setPeriodValue(other.getPeriodValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      me.mervap.message.GUpdateSubscription parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (me.mervap.message.GUpdateSubscription) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private me.mervap.message.GUserName userName_;
    private com.google.protobuf.SingleFieldBuilderV3<
        me.mervap.message.GUserName, me.mervap.message.GUserName.Builder, me.mervap.message.GUserNameOrBuilder> userNameBuilder_;
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     * @return Whether the userName field is set.
     */
    public boolean hasUserName() {
      return userNameBuilder_ != null || userName_ != null;
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     * @return The userName.
     */
    public me.mervap.message.GUserName getUserName() {
      if (userNameBuilder_ == null) {
        return userName_ == null ? me.mervap.message.GUserName.getDefaultInstance() : userName_;
      } else {
        return userNameBuilder_.getMessage();
      }
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    public Builder setUserName(me.mervap.message.GUserName value) {
      if (userNameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userName_ = value;
        onChanged();
      } else {
        userNameBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    public Builder setUserName(
        me.mervap.message.GUserName.Builder builderForValue) {
      if (userNameBuilder_ == null) {
        userName_ = builderForValue.build();
        onChanged();
      } else {
        userNameBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    public Builder mergeUserName(me.mervap.message.GUserName value) {
      if (userNameBuilder_ == null) {
        if (userName_ != null) {
          userName_ =
            me.mervap.message.GUserName.newBuilder(userName_).mergeFrom(value).buildPartial();
        } else {
          userName_ = value;
        }
        onChanged();
      } else {
        userNameBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    public Builder clearUserName() {
      if (userNameBuilder_ == null) {
        userName_ = null;
        onChanged();
      } else {
        userName_ = null;
        userNameBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    public me.mervap.message.GUserName.Builder getUserNameBuilder() {
      
      onChanged();
      return getUserNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    public me.mervap.message.GUserNameOrBuilder getUserNameOrBuilder() {
      if (userNameBuilder_ != null) {
        return userNameBuilder_.getMessageOrBuilder();
      } else {
        return userName_ == null ?
            me.mervap.message.GUserName.getDefaultInstance() : userName_;
      }
    }
    /**
     * <code>.me.mervap.GUserName userName = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        me.mervap.message.GUserName, me.mervap.message.GUserName.Builder, me.mervap.message.GUserNameOrBuilder> 
        getUserNameFieldBuilder() {
      if (userNameBuilder_ == null) {
        userNameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            me.mervap.message.GUserName, me.mervap.message.GUserName.Builder, me.mervap.message.GUserNameOrBuilder>(
                getUserName(),
                getParentForChildren(),
                isClean());
        userName_ = null;
      }
      return userNameBuilder_;
    }

    private com.google.protobuf.Timestamp purchaseDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> purchaseDateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp purchaseDate = 3;</code>
     * @return Whether the purchaseDate field is set.
     */
    public boolean hasPurchaseDate() {
      return purchaseDateBuilder_ != null || purchaseDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp purchaseDate = 3;</code>
     * @return The purchaseDate.
     */
    public com.google.protobuf.Timestamp getPurchaseDate() {
      if (purchaseDateBuilder_ == null) {
        return purchaseDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : purchaseDate_;
      } else {
        return purchaseDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp purchaseDate = 3;</code>
     */
    public Builder setPurchaseDate(com.google.protobuf.Timestamp value) {
      if (purchaseDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        purchaseDate_ = value;
        onChanged();
      } else {
        purchaseDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp purchaseDate = 3;</code>
     */
    public Builder setPurchaseDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (purchaseDateBuilder_ == null) {
        purchaseDate_ = builderForValue.build();
        onChanged();
      } else {
        purchaseDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp purchaseDate = 3;</code>
     */
    public Builder mergePurchaseDate(com.google.protobuf.Timestamp value) {
      if (purchaseDateBuilder_ == null) {
        if (purchaseDate_ != null) {
          purchaseDate_ =
            com.google.protobuf.Timestamp.newBuilder(purchaseDate_).mergeFrom(value).buildPartial();
        } else {
          purchaseDate_ = value;
        }
        onChanged();
      } else {
        purchaseDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp purchaseDate = 3;</code>
     */
    public Builder clearPurchaseDate() {
      if (purchaseDateBuilder_ == null) {
        purchaseDate_ = null;
        onChanged();
      } else {
        purchaseDate_ = null;
        purchaseDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp purchaseDate = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getPurchaseDateBuilder() {
      
      onChanged();
      return getPurchaseDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp purchaseDate = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getPurchaseDateOrBuilder() {
      if (purchaseDateBuilder_ != null) {
        return purchaseDateBuilder_.getMessageOrBuilder();
      } else {
        return purchaseDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : purchaseDate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp purchaseDate = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getPurchaseDateFieldBuilder() {
      if (purchaseDateBuilder_ == null) {
        purchaseDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getPurchaseDate(),
                getParentForChildren(),
                isClean());
        purchaseDate_ = null;
      }
      return purchaseDateBuilder_;
    }

    private int period_ = 0;
    /**
     * <code>.me.mervap.GPeriod period = 4;</code>
     * @return The enum numeric value on the wire for period.
     */
    @java.lang.Override public int getPeriodValue() {
      return period_;
    }
    /**
     * <code>.me.mervap.GPeriod period = 4;</code>
     * @param value The enum numeric value on the wire for period to set.
     * @return This builder for chaining.
     */
    public Builder setPeriodValue(int value) {
      
      period_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.me.mervap.GPeriod period = 4;</code>
     * @return The period.
     */
    @java.lang.Override
    public me.mervap.message.GPeriod getPeriod() {
      @SuppressWarnings("deprecation")
      me.mervap.message.GPeriod result = me.mervap.message.GPeriod.valueOf(period_);
      return result == null ? me.mervap.message.GPeriod.UNRECOGNIZED : result;
    }
    /**
     * <code>.me.mervap.GPeriod period = 4;</code>
     * @param value The period to set.
     * @return This builder for chaining.
     */
    public Builder setPeriod(me.mervap.message.GPeriod value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      period_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.me.mervap.GPeriod period = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPeriod() {
      
      period_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:me.mervap.GUpdateSubscription)
  }

  // @@protoc_insertion_point(class_scope:me.mervap.GUpdateSubscription)
  private static final me.mervap.message.GUpdateSubscription DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new me.mervap.message.GUpdateSubscription();
  }

  public static me.mervap.message.GUpdateSubscription getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GUpdateSubscription>
      PARSER = new com.google.protobuf.AbstractParser<GUpdateSubscription>() {
    @java.lang.Override
    public GUpdateSubscription parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GUpdateSubscription(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GUpdateSubscription> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GUpdateSubscription> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public me.mervap.message.GUpdateSubscription getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

