(load-file "examples/0_1_magic.clj")

(lecture "1. Functions")
(load-file "examples/1_1_intro.clj")
(load-file "examples/1_2_functions.clj")
(load-file "examples/1_3_lists.clj")
(load-file "examples/1_4_vectors.clj")
(load-file "examples/1_5_functions-2.clj")

(lecture "2. Outer world")
(load-file "examples/2_1_io.clj")
(load-file "examples/2_2_read.clj")
(load-file "examples/2_3_evaluation-orders.clj")
(load-file "examples/2_4_streams.clj")
(load-file "examples/2_5_maps.clj")

(lecture "3. Objects and evaluation")
(load-file "examples/3_1_js-objects.clj")
(load-file "examples/3_2_java-objects.clj")
(load-file "examples/3_3_mutable-state.clj")
(load-file "examples/3_4_church.clj")
